In [4]:
import numpy as np

In [11]:
# dekoratif çizgi
dash_line = "\n------------------------------------------------------------\n"

In [6]:

class LVQ1:
    '''LVQ1 : Linear Vector Quantization ile binary sayilarla calisan LVQ1 yapay sinir ağı(YSA) nesnesi oluşturulması
    Bu ağ ile 
    '''
    def __init__(self, lr=0.7):
        '''
        Başlangıç değerlerini ata ve YSA'nın şekil ve sınırlarını belirle
        
        Parametreler:
        -------------

        '''
        # Verilen ilk agirlik degerlerini oznitelik olarak ata
        self.A11 = np.array([3.21, 1.36])
        self.A12 = np.array([3.40, 1.20])
        self.A2 = np.array([3.75, 1.30])

        # Öğrenme katsayısını nesneye nitelik olarak ata 
        self.lr = lr
        # En yakın temsil vektör uzaklığı ve sınıfı hafızada tutmak için
        self.minDist = 0
        self.winner = 0
        
    def learn(self, X, y, show=False, predict=False):
        '''LVQ1 YSA'nı girdi vektörü X ve y ile eğit
            show     : verileri goster
            predict  : sadece tahmin yap (test için)
        '''
        # Uzaklıkları L2 norma gore hesapla
        d1 = np.sqrt(sum((X - self.A11)**2));
        d2 = np.sqrt(sum((X - self.A12)**2));
        d3 = np.sqrt(sum((X - self.A2)**2));
        d = [d1, d2, d3]

        self.winner = np.argmin(d)
        if show:
            print("Uzaklıklar: ")
            print(d)
            print(f"Kazanan: {self.winner}")
        
        if np.all([y == 2, self.winner == 2]):
            self.A2 = self.A2 + self.lr*(X-self.A2)
        if np.all([y == 1, self.winner == 2]):
            self.A2 = self.A2 - self.lr*(X-self.A2)
            
        if np.all([y == 1, self.winner == 1]):
            self.A12 = self.A12 + self.lr*(X-self.A12)
        if np.all([y == 2, self.winner == 1]):
            self.A12 = self.A12 - self.lr*(X-self.A12)
            
        if np.all([y == 1,self.winner == 0]):
            self.A11 = self.A11 + self.lr*(X-self.A11)
        if np.all([y == 2, self.winner == 0]):
            self.A11 = self.A11 - self.lr*(X-self.A11)
        
        return None
        

In [7]:
#1. Örnek
Model = LVQ1(lr=0.7)
veri = np.array([[4.0, 1.3],[5.1, 1.9],[4.6, 1.5],[6.0, 2.5]])
Category = np.array([1, 2, 1, 2])

iterasyon = 4
for i in range(iterasyon):
    X = veri[i]
    print(f"Veri: {X}")
    y = Category[i]
    print(f"Ait olunan sınıf:{y}")
    Model.learn(X, y)
    print(dash_line)

Veri: [4.  1.3]
Ait olunan sınıf:1

------------------------------------------------------------

Veri: [5.1 1.9]
Ait olunan sınıf:2

------------------------------------------------------------

Veri: [4.6 1.5]
Ait olunan sınıf:1

------------------------------------------------------------

Veri: [6.  2.5]
Ait olunan sınıf:2

------------------------------------------------------------



In [8]:
Model.A11

array([3.21, 1.36])

In [9]:
Model.A12

array([3.4, 1.2])

In [10]:
Model.A2

array([5.601675, 2.3122  ])